
---
title: "Codebook for the run_analysis"
output: "tidydata.txt"
---

## Tidy Data 
**Variables**
path: path of raw data source UCI HAR Dataset
feature_list: stored the the features.csv
xtrain - stored the read the X_train.txt
ytrain - stored the read the y_train.txt
subjecttrain - stored the read the subject_train.txt.txt
xtest - stored the read the X_test.txt
ytest - stored the read the y_test.txt
subjecttest - stored the read the subject_test.txt
final_df - merged data of train, test, and subject
means - dataframe consisting activities and subject only
tidydata.txt - output of the run_analysis.R which is the cleaned up data

**Subject ID Number:**
1 - 30

**Activity description**
WALKING
WALKING_UPSTAIRS
WALKING_DOWNSTAIRS
SITTING
STANDING
LAYING

**Features**
The features selected for this database come from the accelerometer
and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time
domain signals (prefix ‘t’ to denote time) were captured at a constant
rate of 50 Hz. Then they were filtered using a median filter and a 3rd
order low pass Butterworth filter with a corner frequency of 20 Hz to
remove noise. Similarly, the acceleration signal was then separated into
body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ)
using another low pass Butterworth filter with a corner frequency of 0.3
Hz.
Value provided is the mean of each feature grouped by activity and subject.

[1] "Subject"
[2] "Activity"
[3] "TimeBodyAccelerometerMeanX"
[4] "TimeBodyAccelerometerMeanY"
[5] "TimeBodyAccelerometerMeanZ"
[6] "TimeBodyAccelerometerStandardDeviationX"
[7] "TimeBodyAccelerometerStandardDeviationY"
[8] "TimeBodyAccelerometerStandardDeviationZ"
[9] "TimeGravityAccelerometerMeanX"
[10] "TimeGravityAccelerometerMeanY"
[11] "TimeGravityAccelerometerMeanZ"
[12] "TimeGravityAccelerometerStandardDeviationX"
[13] "TimeGravityAccelerometerStandardDeviationY"
[14] "TimeGravityAccelerometerStandardDeviationZ"
[15] "TimeBodyAccelerometerJerkMeanX"
[16] "TimeBodyAccelerometerJerkMeanY"
[17] "TimeBodyAccelerometerJerkMeanZ"
[18] "TimeBodyAccelerometerJerkStandardDeviationX"
[19] "TimeBodyAccelerometerJerkStandardDeviationY"
[20] "TimeBodyAccelerometerJerkStandardDeviationZ"
[21] "TimeBodyGyroscopeMeanX"
[22] "TimeBodyGyroscopeMeanY"
[23] "TimeBodyGyroscopeMeanZ"
[24] "TimeBodyGyroscopeStandardDeviationX"
[25] "TimeBodyGyroscopeStandardDeviationY"
[26] "TimeBodyGyroscopeStandardDeviationZ"
[27] "TimeBodyGyroscopeJerkMeanX"
[28] "TimeBodyGyroscopeJerkMeanY"
[29] "TimeBodyGyroscopeJerkMeanZ"
[30] "TimeBodyGyroscopeJerkStandardDeviationX"
[31] "TimeBodyGyroscopeJerkStandardDeviationY"
[32] "TimeBodyGyroscopeJerkStandardDeviationZ"
[33] "TimeBodyAccelerometerMagnitudeMean"
[34] "TimeBodyAccelerometerMagnitudeStandardDeviation"
[35] "TimeGravityAccelerometerMagnitudeMean"
[36] "TimeGravityAccelerometerMagnitudeStandardDeviation"
[37] "TimeBodyAccelerometerJerkMagnitudeMean"
[38] "TimeBodyAccelerometerJerkMagnitudeStandardDeviation"
[39] "TimeBodyGyroscopeMagnitudeMean"
[40] "TimeBodyGyroscopeMagnitudeStandardDeviation"
[41] "TimeBodyGyroscopeJerkMagnitudeMean"
[42] "TimeBodyGyroscopeJerkMagnitudeStandardDeviation"
[43] "FrequencyuencyBodyAccelerometerMeanX"
[44] "FrequencyuencyBodyAccelerometerMeanY"
[45] "FrequencyuencyBodyAccelerometerMeanZ"
[46] "FrequencyuencyBodyAccelerometerStandardDeviationX"
[47] "FrequencyuencyBodyAccelerometerStandardDeviationY"
[48] "FrequencyuencyBodyAccelerometerStandardDeviationZ"
[49] "FrequencyuencyBodyAccelerometerMeanFrequencyX"
[50] "FrequencyuencyBodyAccelerometerMeanFrequencyY"
[51] "FrequencyuencyBodyAccelerometerMeanFrequencyZ"
[52] "FrequencyuencyBodyAccelerometerJerkMeanX"
[53] "FrequencyuencyBodyAccelerometerJerkMeanY"
[54] "FrequencyuencyBodyAccelerometerJerkMeanZ"
[55] "FrequencyuencyBodyAccelerometerJerkStandardDeviationX"
[56] "FrequencyuencyBodyAccelerometerJerkStandardDeviationY"
[57] "FrequencyuencyBodyAccelerometerJerkStandardDeviationZ"
[58] "FrequencyuencyBodyAccelerometerJerkMeanFrequencyX"
[59] "FrequencyuencyBodyAccelerometerJerkMeanFrequencyY"
[60] "FrequencyuencyBodyAccelerometerJerkMeanFrequencyZ"
[61] "FrequencyuencyBodyGyroscopeMeanX"
[62] "FrequencyuencyBodyGyroscopeMeanY"
[63] "FrequencyuencyBodyGyroscopeMeanZ"
[64] "FrequencyuencyBodyGyroscopeStandardDeviationX"
[65] "FrequencyuencyBodyGyroscopeStandardDeviationY"
[66] "FrequencyuencyBodyGyroscopeStandardDeviationZ"
[67] "FrequencyuencyBodyGyroscopeMeanFrequencyX"
[68] "FrequencyuencyBodyGyroscopeMeanFrequencyY"
[69] "FrequencyuencyBodyGyroscopeMeanFrequencyZ"
[70] "FrequencyuencyBodyAccelerometerMagnitudeMean"
[71] "FrequencyuencyBodyAccelerometerMagnitudeStandardDeviation"
[72] "FrequencyuencyBodyAccelerometerMagnitudeMeanFrequency"
[73] "FrequencyuencyBodyAccelerometerJerkMagnitudeMean"
[74] "FrequencyuencyBodyAccelerometerJerkMagnitudeStandardDeviation" [75] "FrequencyuencyBodyAccelerometerJerkMagnitudeMeanFrequency"
[76] "FrequencyuencyBodyGyroscopeMagnitudeMean"
[77] "FrequencyuencyBodyGyroscopeMagnitudeStandardDeviation"
[78] "FrequencyuencyBodyGyroscopeMagnitudeMeanFrequency"
[79] "FrequencyuencyBodyGyroscopeJerkMagnitudeMean"
[80] "FrequencyuencyBodyGyroscopeJerkMagnitudeStandardDeviation"
[81] "FrequencyuencyBodyGyroscopeJerkMagnitudeMeanFrequency"

